---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Run pre-commit hook checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # fetch all history so checks (e.g. gitleaks) can check the full history
          fetch-depth: 0

      - name: Set up mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

      - name: Run checks
        run: |
          hk check --all
        env:
          MISE_ENV: ci
          # specify profile for CI check where all files are checked
          HK_PROFILE: ci-check-all
          # required for some builds, set if available
          GH_PAT: ${{ secrets.GH_PAT }}
